import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/layout/Navbar";
import { Footer } from "@/layout/Footer";
import FloatingWhatsAppButton from "@/components/WhatsappSupport";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Demystified",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <FloatingWhatsAppButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
